//
//  LoginViewModel.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit

protocol LoginViewModel: class {
    func doSomeWork()
}

class DefaultLoginViewModel: LoginViewModel {
    init() {
        
    }
    func doSomeWork() {
    }
}
