//
//  LoginController.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//


class LoginController {
    var router: LoginRouter!
    var viewModel: DefaultLoginViewModel
    weak var displayUI: Login_DisplayUI!
    init(_ viewModel: DefaultLoginViewModel) {
        self.viewModel = viewModel
    }
}
extension LoginController: Login_HandleUIEvents {
    func doSomething() {
        
    }
}
