//
//  LoginAPI.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//


protocol LoginService {
    //func login(request: LoginRequest, completion: (PatientProfile?, MOError?))
}
class LoginAPI: LoginService {
    var connection: NetworkingAPI
    init(_ connection: NetworkingAPI) {
        self.connection = connection
    }
//    func login(request: LoginRequest, completion: (PatientProfile?, MOError?)) {
//        let data = RequestData(endpoint: .login, parameters: nil, body: request.toJSON())
//        connection.makeWebserviceCall(method: .post, with: data) { [weak self] (response: Result<LoginResponse>) in
//            switch response {
//            case .success(let response):
//                UserManager.sharedInstance.patientProfile = response.patient
//                completion(profile, err)
//            case .failure(let err):
//                completion(nil, err)
//            }
//        }
//    }
}
