//
//  LoginModels.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//
enum Login {
    struct Request: JSONDictionaryDeserializable {
        func toJSON() -> [String: Any] {
            return [:]
        }
    }
    struct Response: JSONDictionarySerializable {
        init(json: [String: Any]) throws {
        }
    }
}
