//
//  LoginRouter.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit
enum LoginSegue: String {
    case showDetail = "ShowDetailViewController"
}
final class LoginRouter: BaseNavigation, Navigator {
    
    static func addContracts(_ viewController: LoginViewController) {
        
        let viewModel = DefaultLoginViewModel()
        let controller = LoginController(viewModel)
        let router = LoginRouter(with: viewController)
        controller.router = router
        controller.displayUI = viewController
        viewController.router = router//assigned to instance in BaseViewController
        viewController.eventHandler = controller
        viewController.viewModel = viewModel
    }
    func perform(_ segue: LoginSegue, sender: Any?) {
        guard let actionSegue = LoginSegue(rawValue: segue.rawValue) else { return }
        switch actionSegue {
        case .showDetail:
            viewController.performSegue(withIdentifier: segue.rawValue, sender: sender)
        }
    }
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        guard let identifier = segue.identifier, let actionSegue = LoginSegue(rawValue: identifier) else {
            fatalError("identifier not defined or not matched with defined LoginSegue")
        }
//        switch actionSegue {
//        case .showDetail:
//            guard let viewController = segue.destination as? DetailViewController else {
//                printError("destination class mismatch")
//                return
//            }
//            DetailRouter<DetailSegue>.addContracts(viewController)
//        }
        
    }
    deinit {
        printDebug("\(String(describing: self)) is being deInitialized.")
    }
}

