included:
  - Sample
excluded:
disabled_rules: # rule identifiers to exclude from running
 - trailing_newline
 - trailing_whitespace
#opt_in_rules: # some rules are only opt-in

#  - opening_brace
#  - comma
#  - colon
#  - force_cast
#  - type_name
#  - variable_name_min_length
#  - trailing_semicolon
#  - function_body_length
#  - nesting
#  - variable_name
#  - conditional_binding_cascade
#  - variable_name_max_length
#  - operator_whitespace
#  - control_statement
#  - legacy_constant
#  - line_length
#  - return_arrow_whitespace
#  - trailing_whitespace
#  - closing_brace
#  - statement_position
#  - type_body_length
#  - todo
#  - legacy_constructor
#  - valid_docs
#  - missing_docs
#  - file_length
#  - leading_whitespace
#  - function_parameter_count

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SwiftLint
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Realm\. All rights reserved\.
                    \/\/

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 250
