//
//  LoginViewController.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the ZCo Swift Xcode Templates
//

import UIKit


class LoginViewController: BaseViewController {
    
    var eventHandler: Login_HandleUIEvents!
    weak var viewModel: LoginViewModel!
    @IBOutlet weak var sbControl: LoginSBControl!
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    override class func storyboard() -> UIStoryboard {
        return UIStoryboard.login
    }
}

extension LoginViewController: Login_DisplayUI {
    func toggle(_ isLoading: Bool) {
    }
}
