//
//  LoginContracts.swift
//  Sample
//
//  Created by Admin on 29/01/18.
//  Copyright (c) 2018 jijo. All rights reserved.
//
//  This file was generated by the Zco Xcode Templates
//

import UIKit

protocol Login_HandleUIEvents: class {
    func doSomething()
}

protocol Login_DisplayUI: class {
    func toggle(_ isLoading: Bool)
}
